/* eslint-disable @typescript-eslint/no-explicit-any */
import { createServer as createHttpServer, type IncomingMessage, type Server, type ServerResponse } from "node:http";
import { createServer as createHttpsServer } from "node:https";
import { readFile } from "node:fs/promises";
import path from "node:path";
import { z, ZodError } from "zod";
import type { AdapterConfig, DataLocation, SecretRecord, WebUser } from "./types";
import { SessionStore, safeUser, verifyPassword } from "./web-auth";

export interface WebApi {
 config():AdapterConfig; publicLocation(location:DataLocation):unknown; persistLocation(raw:unknown,secret?:SecretRecord):Promise<unknown>; deleteLocation(id:string):Promise<void>;
 persistJob(raw:unknown):Promise<unknown>; deleteJob(id:string):Promise<void>; testLocation(id:string,write:boolean):Promise<unknown>; browseLocation(id:string,p:string,offset:number,limit:number):Promise<unknown>;
 startRun(id:string,preview:boolean):unknown; run(id:string):unknown; runs(limit:number):unknown[]; runItems(id:string,offset:number,limit:number):unknown; status():unknown;
 tls?():Promise<{key:string|Buffer;cert:string|Buffer;ca?:string|Buffer}>;
}
type Principal={user:WebUser;session:{id:string;csrf:string;expiresAt:number}};
class ApiError extends Error{constructor(readonly status:number,readonly code:string,message="Access denied"){super(message)}}
const locationBody=z.object({location:z.record(z.unknown()),secret:z.object({password:z.string().max(4096).optional(),privateKey:z.string().max(131072).optional(),passphrase:z.string().max(4096).optional()}).optional()});
const jobBody=z.object({job:z.record(z.unknown())});
export class StandaloneWebServer{
 private server?:Server;private sessions:SessionStore;private failures=new Map<string,{count:number;blockedUntil:number}>();
 constructor(private api:WebApi,private root:string,private secure:boolean,ttlMinutes:number){this.sessions=new SessionStore(ttlMinutes)}
 async start(port:number,bind:string){const handler=(req:IncomingMessage,res:ServerResponse)=>void this.handle(req,res);this.server=this.secure?createHttpsServer(await this.requireTls(),handler):createHttpServer(handler);await new Promise<void>((resolve,reject)=>{this.server!.once("error",reject);this.server!.listen(port,bind,()=>{this.server!.off("error",reject);resolve()})})}
 async stop(){this.sessions.close();if(this.server)await new Promise<void>((resolve,reject)=>this.server!.close(e=>e?reject(e):resolve()))}
 get port(){const address=this.server?.address();return typeof address==="object"&&address?address.port:undefined}
 get loggedInUsers(){return this.sessions.size}
 private async requireTls(){if(!this.api.tls)throw new Error("HTTPS requires an ioBroker certificate collection");return this.api.tls()}
 private headers(res:ServerResponse,api=false){res.setHeader("X-Content-Type-Options","nosniff");res.setHeader("X-Frame-Options","DENY");res.setHeader("Referrer-Policy","no-referrer");res.setHeader("Content-Security-Policy","default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; connect-src 'self'; frame-ancestors 'none'; base-uri 'none'; form-action 'self'");if(api)res.setHeader("Cache-Control","no-store");if(this.secure)res.setHeader("Strict-Transport-Security","max-age=31536000")}
 private json(res:ServerResponse,status:number,value:unknown){this.headers(res,true);res.statusCode=status;res.setHeader("Content-Type","application/json; charset=utf-8");res.end(JSON.stringify(value))}
 private error(res:ServerResponse,error:unknown){const known=error instanceof ApiError?error:error instanceof ZodError?new ApiError(400,"VALIDATION_ERROR","Invalid request"):new ApiError(500,"INTERNAL_ERROR","Request failed");this.json(res,known.status,{ok:false,error:{code:known.code,message:known.message}})}
 private async body(req:IncomingMessage){let size=0;const chunks:Buffer[]=[];for await(const chunk of req){size+=chunk.length;if(size>1024*1024)throw new ApiError(413,"BODY_TOO_LARGE","Request body too large");chunks.push(chunk)}try{return chunks.length?JSON.parse(Buffer.concat(chunks).toString("utf8")):{} }catch{throw new ApiError(400,"INVALID_JSON","Invalid JSON")}}
 private cookie(req:IncomingMessage){return req.headers.cookie?.split(";").map(x=>x.trim().split("=")).find(x=>x[0]==="filesync_session")?.[1]}
 private principal(req:IncomingMessage):Principal{const session=this.sessions.get(this.cookie(req));const user=session&&this.api.config().webUsers.find(x=>x.id===session.userId&&x.enabled);if(!session||!user)throw new ApiError(401,"AUTH_REQUIRED","Authentication required");return{user,session}}
 private csrf(req:IncomingMessage,p:Principal){if(req.headers["x-csrf-token"]!==p.session.csrf)throw new ApiError(403,"CSRF_INVALID","CSRF token invalid");const origin=req.headers.origin;if(origin){const host=req.headers.host;if(new URL(origin).host!==host)throw new ApiError(403,"ORIGIN_INVALID","Origin denied")}}
 private can(user:WebUser,groups:string[]){return user.admin||groups.some(id=>user.groupIds.includes(id)&&this.api.config().webGroups.some(group=>group.id===id&&group.enabled))}
 private location(user:WebUser,id:string){const value=this.api.config().locations.find(x=>x.id===id);if(!value)throw new ApiError(404,"LOCATION_NOT_FOUND","Location not found");if(!this.can(user,value.groupIds))throw new ApiError(403,"LOCATION_FORBIDDEN");return value}
 private job(user:WebUser,id:string){const value=this.api.config().jobs.find(x=>x.id===id);if(!value)throw new ApiError(404,"JOB_NOT_FOUND","Job not found");if(!this.can(user,value.groupIds))throw new ApiError(403,"JOB_FORBIDDEN");return value}
 private validateGroups(user:WebUser,groups:unknown){if(!Array.isArray(groups)||groups.some(x=>typeof x!=="string")||(!user.admin&&groups.some(x=>!user.groupIds.includes(x))))throw new ApiError(403,"GROUP_FORBIDDEN");if(groups.length===0&&!user.admin)throw new ApiError(400,"GROUP_REQUIRED","At least one group is required")}
 private validateJobAccess(user:WebUser,raw:Record<string,unknown>){this.validateGroups(user,raw.groupIds);const source=this.location(user,String(raw.sourceLocationId)),target=this.location(user,String(raw.targetLocationId));if(!user.admin){const groups=raw.groupIds as string[];if(!groups.some(id=>source.groupIds.includes(id))||!groups.some(id=>target.groupIds.includes(id)))throw new ApiError(400,"JOB_LOCATION_GROUP_MISMATCH","Job and locations must share a group")}}
 private async login(req:IncomingMessage,res:ServerResponse){const body=z.object({username:z.string().min(1).max(128),password:z.string().min(1).max(1024)}).parse(await this.body(req));const key=`${req.socket.remoteAddress??"unknown"}|${body.username.toLocaleLowerCase()}`,failure=this.failures.get(key);if(failure&&failure.blockedUntil>Date.now())throw new ApiError(429,"LOGIN_RATE_LIMITED","Too many login attempts; try again later");const user=this.api.config().webUsers.find(x=>x.username.toLocaleLowerCase()===body.username.toLocaleLowerCase());if(!user?.enabled||!await verifyPassword(body.password,user.passwordHash)){const count=(failure?.count??0)+1;this.failures.set(key,{count,blockedUntil:count>=5?Date.now()+Math.min(300_000,2**(count-5)*10_000):0});throw new ApiError(401,"INVALID_CREDENTIALS","Benutzername oder Passwort falsch")}this.failures.delete(key);this.sessions.delete(this.cookie(req));const session=this.sessions.create(user.id);res.setHeader("Set-Cookie",`filesync_session=${session.id}; HttpOnly; SameSite=Strict; Path=/; Max-Age=${Math.floor((session.expiresAt-Date.now())/1000)}${this.secure?"; Secure":""}`);this.json(res,200,{ok:true,data:{user:safeUser(user,this.api.config().webGroups),csrfToken:session.csrf}})}
 private runVisible(user:WebUser,record:any){if(user.admin)return true;const job=this.api.config().jobs.find(x=>x.id===record?.jobId);return Boolean(job&&this.can(user,job.groupIds))}
 private async apiRequest(req:IncomingMessage,res:ServerResponse,url:URL){const method=req.method??"GET",parts=url.pathname.split("/").filter(Boolean);if(url.pathname==="/api/auth/login"&&method==="POST"){await this.login(req,res);return}const p=this.principal(req);if(method!=="GET")this.csrf(req,p);
  if(url.pathname==="/api/auth/me"&&method==="GET")return this.json(res,200,{ok:true,data:{...safeUser(p.user,this.api.config().webGroups),csrfToken:p.session.csrf}});
  if(url.pathname==="/api/auth/logout"&&method==="POST"){this.sessions.delete(p.session.id);res.setHeader("Set-Cookie",`filesync_session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0${this.secure?"; Secure":""}`);return this.json(res,200,{ok:true,data:true})}
  if(url.pathname==="/api/status"&&method==="GET"){const visibleJobs=this.api.config().jobs.filter(x=>this.can(p.user,x.groupIds)),visibleRuns=this.api.runs(500).filter(x=>this.runVisible(p.user,x)) as any[];const status=this.api.status() as Record<string,unknown>;return this.json(res,200,{ok:true,data:{...status,locations:this.api.config().locations.filter(x=>this.can(p.user,x.groupIds)).length,jobs:visibleJobs.length,activeJobs:visibleRuns.filter(x=>x.status==="running").length,failedJobs:visibleRuns.filter(x=>x.status==="error").length,queue:visibleRuns.filter(x=>x.status==="queued").length}})}
  if(parts[1]==="locations"){const id=parts[2];if(!id&&method==="GET")return this.json(res,200,{ok:true,data:this.api.config().locations.filter(x=>this.can(p.user,x.groupIds)).map(x=>this.api.publicLocation(x))});if(!id&&method==="POST"){const b=locationBody.parse(await this.body(req));this.validateGroups(p.user,b.location.groupIds);return this.json(res,201,{ok:true,data:await this.api.persistLocation(b.location,b.secret)});}const existing=this.location(p.user,id);if(parts[3]==="test"&&method==="POST")return this.json(res,200,{ok:true,data:await this.api.testLocation(id,Boolean((await this.body(req) as any).writeTest))});if(parts[3]==="browse"&&method==="GET")return this.json(res,200,{ok:true,data:await this.api.browseLocation(id,url.searchParams.get("path")??"",Number(url.searchParams.get("offset")??0),Number(url.searchParams.get("limit")??200))});if(method==="GET")return this.json(res,200,{ok:true,data:this.api.publicLocation(existing)});if(method==="PUT"){const b=locationBody.parse(await this.body(req));if(b.location.id!==id)throw new ApiError(400,"ID_MISMATCH","ID mismatch");this.validateGroups(p.user,b.location.groupIds);return this.json(res,200,{ok:true,data:await this.api.persistLocation(b.location,b.secret)});}if(method==="DELETE"){await this.api.deleteLocation(id);return this.json(res,200,{ok:true,data:true})}}
  if(parts[1]==="jobs"){const id=parts[2];if(!id&&method==="GET")return this.json(res,200,{ok:true,data:this.api.config().jobs.filter(x=>this.can(p.user,x.groupIds))});if(!id&&method==="POST"){const b=jobBody.parse(await this.body(req));this.validateJobAccess(p.user,b.job);return this.json(res,201,{ok:true,data:await this.api.persistJob(b.job)});}const existing=this.job(p.user,id);if(parts[3]==="preview"&&method==="POST")return this.json(res,202,{ok:true,data:this.api.startRun(id,true)});if(parts[3]==="run"&&method==="POST")return this.json(res,202,{ok:true,data:this.api.startRun(id,false)});if(method==="GET")return this.json(res,200,{ok:true,data:existing});if(method==="PUT"){const b=jobBody.parse(await this.body(req));if(b.job.id!==id)throw new ApiError(400,"ID_MISMATCH","ID mismatch");this.validateJobAccess(p.user,b.job);return this.json(res,200,{ok:true,data:await this.api.persistJob(b.job)});}if(method==="DELETE"){await this.api.deleteJob(id);return this.json(res,200,{ok:true,data:true})}}
  if(parts[1]==="runs"){if(!parts[2]&&method==="GET")return this.json(res,200,{ok:true,data:this.api.runs(Number(url.searchParams.get("limit")??100)).filter(x=>this.runVisible(p.user,x))});const record=this.api.run(parts[2]);if(!record||!this.runVisible(p.user,record))throw new ApiError(404,"RUN_NOT_FOUND","Run not found");if(parts[3]==="items")return this.json(res,200,{ok:true,data:this.api.runItems(parts[2],Number(url.searchParams.get("offset")??0),Number(url.searchParams.get("limit")??200))});return this.json(res,200,{ok:true,data:record})}
  throw new ApiError(404,"NOT_FOUND","Not found")
 }
 private async handle(req:IncomingMessage,res:ServerResponse){try{const url=new URL(req.url??"/",`${this.secure?"https":"http"}://${req.headers.host??"localhost"}`);if(url.pathname.startsWith("/api/")){await this.apiRequest(req,res,url);return}const relative=url.pathname==="/"?"index.html":url.pathname.slice(1);const safe=path.resolve(this.root,relative);if(!safe.startsWith(path.resolve(this.root)+path.sep))throw new ApiError(404,"NOT_FOUND","Not found");let data:Buffer;try{data=await readFile(safe)}catch{data=await readFile(path.join(this.root,"index.html"))}this.headers(res);res.setHeader("Content-Type",safe.endsWith(".js")?"text/javascript; charset=utf-8":safe.endsWith(".css")?"text/css; charset=utf-8":"text/html; charset=utf-8");res.setHeader("Cache-Control",safe.endsWith("index.html")?"no-cache":"public, max-age=3600");res.end(data)}catch(error){this.error(res,error)}}
}
