import{describe,it,expect}from"vitest";import{normalizeRelative,safeLocalPath}from"../src/lib/security/path";import{redact}from"../src/lib/security/redact";import{retry}from"../src/lib/utils/retry";import{JobLock}from"../src/lib/jobs/lock";import{NotificationGate}from"../src/lib/notifications/gate";import{Authorizer}from"../src/lib/permissions/authorizer";import{changed,matches}from"../src/lib/sync/filter";import{migrateConfig,validateJob,validateLocation,validateRelations}from"../src/lib/config";
describe("security",()=>{it("normalizes separators and denies traversal",()=>{expect(normalizeRelative("/a\\b/../c")).toBe("a/c");expect(()=>normalizeRelative("../../etc")).toThrow();expect(()=>safeLocalPath("/safe","../etc")).toThrow()});it("accepts normal descendants when the local root is the filesystem root",()=>{expect(safeLocalPath("/","tmp/example")).toBe("/tmp/example");expect(()=>safeLocalPath("/safe","../etc")).toThrow()});it("redacts keys and known values",()=>{expect(redact({password:"visible",message:"token=abc secret-value"},["secret-value"])).toEqual({password:"[REDACTED]",message:"token=[REDACTED] [REDACTED]"})})});
describe("reliability",()=>{it("retries with bounded attempts",async()=>{let calls=0;await expect(retry(async()=>{if(++calls<3)throw Error("offline");return 7},{attempts:2,baseDelayMs:1,exponential:true,maxDelayMs:2},async()=>undefined)).resolves.toBe(7);expect(calls).toBe(3)});it.each([[false,false,{realRequested:true,previewRequested:false}],[true,true,{realRequested:false,previewRequested:true}],[false,true,{realRequested:false,previewRequested:true}],[true,false,{realRequested:true,previewRequested:false}]])("coalesces pending intents (%s, %s)",(running,incoming,expected)=>{const l=new JobLock();expect(l.tryAcquire("a",running)).toBe(true);expect(l.tryAcquire("a",incoming)).toBe(false);expect(l.release("a")).toEqual(expected)});it("retains both real and preview requests",()=>{const l=new JobLock();l.tryAcquire("a",false);l.tryAcquire("a",false);l.tryAcquire("a",true);expect(l.release("a")).toEqual({realRequested:true,previewRequested:true})});it("gates notifications and emits one recovery",()=>{const g=new NotificationGate();expect(g.failure("a",100,0)).toBe(true);expect(g.failure("a",100,50)).toBe(false);expect(g.recovery("a")).toBe(true);expect(g.recovery("a")).toBe(false)})});
describe("configuration",()=>{it("migrates safe defaults",()=>{const c=migrateConfig({});expect(c.configVersion).toBe(1);expect(c.maxConcurrentTransfers).toBe(2)});it("enforces resource permissions",()=>{const a=new Authorizer([{id:"g",name:"g",users:["system.user.u"],permissions:["jobs.view"],locationIds:[],jobIds:["j"]}]);expect(a.can("system.user.u","jobs.view",{type:"job",id:"j"})).toBe(true);expect(a.can("system.user.u","jobs.view",{type:"job",id:"x"})).toBe(false)})});
describe("change detection",()=>{const f={path:"folder/ä.pdf",name:"ä.pdf",type:"file" as const,size:1,mtimeMs:10};it("compares size and mtime",()=>{expect(changed(f,{...f})).toBe(false);expect(changed(f,{...f,size:2})).toBe(true)});it("applies glob and ignores transfer files",()=>{expect(matches(f,{include:["**/*.pdf"],exclude:["*.tmp"]})).toBe(true);expect(matches({...f,path:".x.filesync-abc.tmp"},{include:[],exclude:[]})).toBe(false)})});


describe("Admin transport boundary",()=>{
 it("rejects payloads and non-Admin senders",async()=>{const {assertAdminTransport}=await import("../src/lib/permissions/principal");expect(()=>assertAdminTransport({from:"system.adapter.javascript.0"})).toThrow();expect(()=>assertAdminTransport({from:"system.user.admin"})).toThrow()});
 it("accepts controller messages from an Admin instance",async()=>{const {assertAdminTransport}=await import("../src/lib/permissions/principal");expect(()=>assertAdminTransport({from:"system.adapter.admin.0"})).not.toThrow()});
});

describe("credential ownership",()=>{
 it("ignores a client credential id for new and existing locations",async()=>{const {secureLocationCredentialId}=await import("../src/lib/config");const raw={type:"smb",credentialId:"00000000-0000-4000-8000-000000000001"};const created=secureLocationCredentialId(raw) as typeof raw;expect(created.credentialId).not.toBe(raw.credentialId);const existing={...raw,id:"00000000-0000-4000-8000-000000000002",name:"x",enabled:true,readOnly:false,timeoutMs:1000,host:"h",port:445,share:"s",username:"u",basePath:""} as const;const updated=secureLocationCredentialId({...raw,credentialId:"00000000-0000-4000-8000-000000000003"},existing) as typeof raw;expect(updated.credentialId).toBe(existing.credentialId)});
});

describe("reconciliation",()=>{
 const file={path:"a.pdf",name:"a.pdf",type:"file" as const,size:10,mtimeMs:100};
 it("repairs missing and size-mismatched targets",async()=>{const {targetNeedsRepair}=await import("../src/lib/sync/reconciliation");expect(targetNeedsRepair(file,undefined)).toBe(true);expect(targetNeedsRepair(file,{...file,size:9})).toBe(true);expect(targetNeedsRepair(file,{...file})).toBe(false)});
 it("requires two unchanged observations across the full window",async()=>{const {stableSince}=await import("../src/lib/sync/reconciliation");expect(stableSince(file,undefined,1000,2000)).toBe(false);expect(stableSince(file,{size:11,mtimeMs:100,observedAt:0},1000,2000)).toBe(false);expect(stableSince(file,{size:10,mtimeMs:99,observedAt:0},1000,2000)).toBe(false);expect(stableSince(file,{size:10,mtimeMs:100,observedAt:1500},1000,2000)).toBe(false);expect(stableSince(file,{size:10,mtimeMs:100,observedAt:500},1000,2000)).toBe(true)});
 it("keeps out-of-scope mirror targets",()=>{expect(matches({...file,path:"wichtig.xlsx"},{include:["**/*.pdf"],exclude:[]})).toBe(false);expect(matches({...file,path:"private.pdf"},{include:["**/*.pdf"],exclude:["private.pdf"]})).toBe(false)});
});


describe("job safety validation",()=>{
 it("rejects version conflict mode for mirror jobs",()=>{const now="2026-01-01T00:00:00.000Z";expect(()=>validateJob({id:"00000000-0000-4000-8000-000000000003",name:"j",enabled:true,sourceLocationId:"00000000-0000-4000-8000-000000000001",sourcePath:"",targetLocationId:"00000000-0000-4000-8000-000000000002",targetPath:"",mode:"mirror",mirrorDeleteConfirmed:true,dryRun:false,recursive:true,preserveTimestamps:false,hashCheck:false,stabilitySeconds:0,conflict:"version",trigger:{type:"manual",intervalSeconds:30},filters:{include:[],exclude:[]},retry:{attempts:0,baseDelayMs:100,exponential:false,maxDelayMs:100},notificationGroupIds:[],createdAt:now,updatedAt:now})).toThrow("Version conflict mode is not supported for mirror jobs")});
 it("uses only the host platform for local absolute paths",()=>{if(process.platform!=="win32")expect(()=>validateLocation({id:"00000000-0000-4000-8000-000000000001",name:"x",type:"local",enabled:true,readOnly:false,timeoutMs:1000,basePath:"C:\\Data"})).toThrow()});
 it("rejects a read-only target",()=>{const source={id:"00000000-0000-4000-8000-000000000001",name:"source",type:"local" as const,enabled:true,readOnly:true,timeoutMs:1000,basePath:"/source"},target={...source,id:"00000000-0000-4000-8000-000000000002",name:"target",basePath:"/target"};const j={id:"00000000-0000-4000-8000-000000000003",name:"j",enabled:true,sourceLocationId:source.id,sourcePath:"",targetLocationId:target.id,targetPath:"",mode:"incremental" as const,mirrorDeleteConfirmed:false,dryRun:false,recursive:true,preserveTimestamps:false,hashCheck:false,stabilitySeconds:0,conflict:"changed" as const,trigger:{type:"manual" as const,intervalSeconds:30},filters:{include:[],exclude:[]},retry:{attempts:0,baseDelayMs:100,exponential:false,maxDelayMs:100},notificationGroupIds:[],createdAt:"2026-01-01T00:00:00.000Z",updatedAt:"2026-01-01T00:00:00.000Z"};expect(()=>validateRelations({...migrateConfig({}),locations:[source,target]},j)).toThrow(/read-only/)});
});

describe("global transfer limiter",()=>{
 it("limits transfers across jobs and reports the actual waiting queue",async()=>{const {TransferLimiter}=await import("../src/lib/jobs/transfer-limit");const limiter=new TransferLimiter(2);let active=0,maximum=0;let release!:()=>void;const gate=new Promise<void>(resolve=>{release=resolve});const operations=Array.from({length:4},()=>limiter.run(async()=>{active++;maximum=Math.max(maximum,active);await gate;active--}));await new Promise(resolve=>setTimeout(resolve,5));expect(limiter.activeCount).toBe(2);expect(limiter.pendingCount).toBe(2);release();await Promise.all(operations);expect(maximum).toBe(2);expect(limiter.pendingCount).toBe(0)});
});
