import {mkdtemp,readFile,rm} from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import {afterEach,describe,expect,it} from "vitest";
import {RunManager} from "../src/lib/runs/manager";

const roots:string[]=[];
afterEach(async()=>Promise.all(roots.splice(0).map(root=>rm(root,{recursive:true,force:true}))));
async function manager(retention=500){const root=await mkdtemp(path.join(os.tmpdir(),"filesync-runs-"));roots.push(root);const value=new RunManager(root,String,retention,20);await value.load();return{root,value}}

describe("RunManager",()=>{
 it("persists file actions for productive runs and an explicit empty result for no-op runs",async()=>{const {root,value}=await manager();const changed=value.enqueue("job","manual",false,async()=>({summary:{copied:1},items:[{path:"hello.txt",action:"copy"}],total:1}));const noop=value.enqueue("other","manual",false,async()=>({summary:{copied:0},items:[],total:0}));await value.shutdown();expect(value.getItems(changed.runId).items).toEqual([{path:"hello.txt",action:"copy"}]);expect(value.getItems(noop.runId)).toMatchObject({total:0,items:[]});const restored=new RunManager(root,String);await restored.load();expect(restored.getItems(changed.runId).items[0]).toMatchObject({path:"hello.txt",action:"copy"});await restored.shutdown()});
 it("keeps a queued invocation tied to its run id until it really executes",async()=>{const {value}=await manager();let release!:()=>void;const first=value.enqueue("job","manual",false,()=>new Promise(resolve=>{release=()=>resolve({summary:{first:true}})}));const second=value.enqueue("job","preview",true,async()=>({summary:{second:true},items:[],total:0}));await new Promise(resolve=>setTimeout(resolve,10));expect(value.get(first.runId)?.status).toBe("running");expect(value.get(second.runId)?.status).toBe("queued");release();await new Promise(resolve=>setTimeout(resolve,20));expect(value.get(second.runId)?.status).toBe("success");await value.shutdown()});
 it("removes old records from memory and its atomic persistent history",async()=>{const {root,value}=await manager(5);for(let i=0;i<10;i++)value.enqueue(`job-${i}`,"schedule",false,async()=>({summary:{}}));await value.shutdown();expect(value.retainedCount).toBe(5);const saved=JSON.parse(await readFile(path.join(root,"runs.json"),"utf8")) as unknown[];expect(saved).toHaveLength(5)});
 it("redacts errors and caps result pagination",async()=>{const {value}=await manager();const run=value.enqueue("job","preview",true,async()=>{throw new Error("secret")});await new Promise(resolve=>setTimeout(resolve,20));expect(value.get(run.runId)?.redactedError).toContain("secret");expect(value.getItems(run.runId,0,999).limit).toBe(500);await value.shutdown()});
 it("coalesces repeated automatic triggers to one waiting run",async()=>{const {value}=await manager();let release!:()=>void;value.enqueue("job","schedule",false,()=>new Promise(resolve=>{release=()=>resolve({})}));await new Promise(resolve=>setTimeout(resolve,10));const waiting=value.enqueue("job","reconciliation",false,async()=>({}));const duplicate=value.enqueue("job","change",false,async()=>({}));expect(duplicate.runId).toBe(waiting.runId);expect(duplicate.coalesced).toBe(true);release();await new Promise(resolve=>setTimeout(resolve,20));await value.shutdown()});
 it("rejects more than ten queued manual runs per job",async()=>{const {value}=await manager();let release!:()=>void;value.enqueue("job","manual",false,()=>new Promise(resolve=>{release=()=>resolve({})}));await new Promise(resolve=>setTimeout(resolve,10));for(let i=0;i<10;i++)value.enqueue("job","manual",false,async()=>({}));expect(()=>value.enqueue("job","preview",true,async()=>({}))).toThrow("Manual run queue limit reached");release();await value.shutdown()});
});
