/* eslint-disable @typescript-eslint/no-explicit-any */
import {afterEach,beforeEach,describe,expect,it} from "vitest";import path from "node:path";import type{AdapterConfig,DataLocation,Job}from "../src/lib/types";import{hashPassword}from "../src/lib/web-auth";import{StandaloneWebServer,type WebApi}from "../src/lib/web-server";
const group=(id:string)=>({id,name:id,description:"",enabled:true,users:[],permissions:[],locationIds:[],jobIds:[]});
const location=(id:string,groupIds:string[]):DataLocation=>({id,name:id,type:"local",basePath:"/tmp",description:"",enabled:true,readOnly:false,timeoutMs:30000,groupIds});
function baseConfig():AdapterConfig{return{configVersion:2,web:{enabled:true,port:0,secure:false,bind:"127.0.0.1",sessionTtlMinutes:60},webGroups:[group("A"),group("B")],webUsers:[],locations:[location("location-a",["A"]),location("location-b",["B"])],jobs:[],groups:[],notifications:[],maxConcurrentTransfers:2,healthIntervalSeconds:300,auditRetention:500,credentialVault:"{}"}}
describe("standalone API authorization",()=>{let server:StandaloneWebServer,cfg:AdapterConfig,base:string;beforeEach(async()=>{cfg=baseConfig();cfg.webUsers=[{id:"a",username:"alice",displayName:"Alice",enabled:true,admin:false,groupIds:["A"],passwordHash:await hashPassword("alice-password")},{id:"admin",username:"admin",displayName:"Admin",enabled:true,admin:true,groupIds:[],passwordHash:await hashPassword("admin-password")}];const api:WebApi={config:()=>cfg,publicLocation:x=>x,persistLocation:async raw=>{cfg.locations.push(raw as DataLocation);return raw},deleteLocation:async()=>{},persistJob:async raw=>raw,deleteJob:async()=>{},testLocation:async()=>({}),browseLocation:async id=>({id}),startRun:id=>({runId:id}),run:()=>null,runs:()=>[],runItems:()=>({}),status:()=>({connected:true})};server=new StandaloneWebServer(api,path.resolve("web-src"),false,60);await server.start(0,"127.0.0.1");base=`http://127.0.0.1:${server.port}`});afterEach(async()=>server.stop());
 async function login(username="alice",password="alice-password"){const response=await fetch(`${base}/api/auth/login`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({username,password})});const data=await response.json() as any;return{response,data,cookie:response.headers.get("set-cookie")?.split(";")[0]??"",csrf:data.data?.csrfToken}}
 it("logs in, exposes safe current user, sets hardened cookie and logs out",async()=>{const auth=await login();expect(auth.response.status).toBe(200);expect(auth.response.headers.get("set-cookie")).toContain("HttpOnly");expect(auth.response.headers.get("set-cookie")).toContain("SameSite=Strict");const me=await fetch(`${base}/api/auth/me`,{headers:{cookie:auth.cookie}});expect((await me.json()as any).data).not.toHaveProperty("passwordHash");const logout=await fetch(`${base}/api/auth/logout`,{method:"POST",headers:{cookie:auth.cookie,"x-csrf-token":auth.csrf}});expect(logout.status).toBe(200);expect((await fetch(`${base}/api/auth/me`,{headers:{cookie:auth.cookie}})).status).toBe(401)});
 it("returns the same login failure for unknown, disabled and wrong credentials",async()=>{for(const [u,p]of [["unknown","anything"],["alice","wrong"],["disabled","anything"]]){const x=await login(u,p);expect(x.response.status).toBe(401);expect(x.data.error.message).toBe("Benutzername oder Passwort falsch")}});
 it("filters collections and blocks direct access, browse and foreign jobs",async()=>{const auth=await login();const headers={cookie:auth.cookie};const list=await(await fetch(`${base}/api/locations`,{headers})).json()as any;expect(list.data.map((x:any)=>x.id)).toEqual(["location-a"]);expect((await fetch(`${base}/api/locations/location-b`,{headers})).status).toBe(403);expect((await fetch(`${base}/api/locations/location-b/browse`,{headers})).status).toBe(403);cfg.jobs.push({id:"job-b",name:"B",enabled:true,groupIds:["B"]}as Job);expect((await fetch(`${base}/api/jobs/job-b/run`,{method:"POST",headers:{...headers,"x-csrf-token":auth.csrf}})).status).toBe(403)});
 it("lets web admins see every group resource and requires CSRF on mutations",async()=>{const auth=await login("admin","admin-password"),headers={cookie:auth.cookie};const list=await(await fetch(`${base}/api/locations`,{headers})).json()as any;expect(list.data).toHaveLength(2);expect((await fetch(`${base}/api/locations/location-a`,{method:"DELETE",headers})).status).toBe(403)});
 it("returns all active groups to a web administrator",async()=>{const auth=await login("admin","admin-password");const response=await fetch(`${base}/api/auth/me`,{headers:{cookie:auth.cookie}});const body=await response.json()as any;expect(body.data.groups).toEqual([{id:"A",name:"A"},{id:"B",name:"B"}])});
 it("never caches the HTML, JavaScript or stylesheet",async()=>{for(const resource of ["/","/app.js","/app.css"]){const response=await fetch(base+resource);expect(response.headers.get("cache-control")).toBe("no-store")}});
 it("rate limits repeated failed logins",async()=>{let status=0;for(let i=0;i<6;i++)status=(await login("attacker","wrong")).response.status;expect(status).toBe(429)})});
