import assert from "node:assert/strict";
import os from "node:os";
import path from "node:path";
import {mkdtemp,rm} from "node:fs/promises";
import {chromium} from "playwright";
import {StandaloneWebServer} from "../../build/lib/web-server.js";
import {hashPassword} from "../../build/lib/web-auth.js";

const root=await mkdtemp(path.join(os.tmpdir(),"filesync-browser-"));
const group={id:"test",name:"Test",description:"",enabled:true,users:[],permissions:[],locationIds:[],jobIds:[]};
const cfg={configVersion:2,web:{enabled:true,port:0,secure:false,bind:"127.0.0.1",sessionTtlMinutes:60},webGroups:[group],webUsers:[{id:"admin",username:"admin",displayName:"Admin",enabled:true,admin:true,groupIds:[],passwordHash:await hashPassword("browser-password")}],locations:[],jobs:[],groups:[],notifications:[],maxConcurrentTransfers:2,healthIntervalSeconds:300,auditRetention:50,credentialVault:"{}"};
const runRecords=[{runId:"run-copy",jobId:"browser-job",source:"manual",dryRun:false,status:"success",queuedAt:Date.now(),startedAt:Date.now()-10,finishedAt:Date.now(),summary:{scanned:1,copied:1}},{runId:"run-noop",jobId:"browser-job",source:"preview",dryRun:true,status:"success",queuedAt:Date.now()-100,startedAt:Date.now()-90,finishedAt:Date.now()-80,summary:{scanned:1,copied:0}}];
const api={config:()=>cfg,publicLocation:x=>({...x,target:x.basePath}),persistLocation:async x=>{const i=cfg.locations.findIndex(y=>y.id===x.id);i<0?cfg.locations.push(x):cfg.locations[i]=x;return x},deleteLocation:async()=>{},persistJob:async x=>{cfg.jobs.push(x);return x},deleteJob:async()=>{},testLocation:async()=>({}),browseLocation:async()=>({entries:[],hasMore:false}),startRun:()=>({runId:"run-copy"}),run:id=>runRecords.find(x=>x.runId===id)||null,runs:()=>runRecords,runItems:id=>({total:id==="run-copy"?1:0,offset:0,limit:200,items:id==="run-copy"?[{path:"hello.txt",action:"copy"}]:[]}),status:()=>({version:"0.1.0",connected:true,webServer:true})};
const server=new StandaloneWebServer(api,path.resolve("web-dist"),false,60);let browser;
try{
 await server.start(0,"127.0.0.1");browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:500,height:700}});const pageErrors=[],consoleErrors=[];
 page.on("pageerror",error=>pageErrors.push(error.message));page.on("console",message=>{if(message.type()==="error")consoleErrors.push(message.text())});
 const responses=[];page.on("response",response=>{if(response.request().method()==="POST")responses.push([new URL(response.url()).pathname,response.status()])});
 await page.goto(`http://127.0.0.1:${server.port}`);await page.locator('[name="username"]').fill("admin");await page.locator('[name="password"]').fill("browser-password");await page.getByRole("button",{name:"Anmelden"}).click();
 await page.getByRole("button",{name:"Datenorte"}).click();await page.locator("#add-location").click();await page.locator(".modal").waitFor({state:"visible"});await page.locator('.modal [name="name"]').fill("Source");await page.locator('.modal [name="basePath"]').fill("/tmp/filesync-source");assert.equal(await page.locator('.modal fieldset.groups input[name="groupIds"]').count(),1);assert.equal(await page.locator('.modal fieldset.groups label:has-text("Test")').count(),1);assert.equal(await page.locator('.modal fieldset.groups input:not(label input)').count(),0);await page.locator('.modal button[type="submit"]').click();await page.getByText("Source",{exact:true}).waitFor();
 await page.locator("#add-location").click();await page.locator('.modal [name="name"]').fill("Target");await page.locator('.modal [name="basePath"]').fill("/tmp/filesync-target");await page.locator('.modal button[type="submit"]').click();await page.getByText("Target",{exact:true}).waitFor();
 await page.getByRole("button",{name:"Jobs"}).click();await page.locator("#add-job").click();await page.locator(".modal").waitFor({state:"visible"});const infos=page.locator(".modal .info");await infos.first().evaluate(button=>Object.assign(button.style,{position:"fixed",left:"0",top:"100px"}));await infos.first().click();let tip=await page.locator(".help-popover").boundingBox();assert.ok(tip&&tip.x>=0);await infos.last().evaluate(button=>Object.assign(button.style,{position:"fixed",right:"0",top:"100px"}));await infos.last().click();tip=await page.locator(".help-popover").boundingBox();assert.ok(tip&&tip.x+tip.width<=500);assert.equal(await page.locator(".help-popover").isVisible(),true);assert.equal(await page.locator('.modal [name="dryRun"]').isChecked(),true);assert.deepEqual(await page.locator('.modal [name="sourceLocationId"] option').allTextContents(),["Bitte wählen","Source (LOCAL)","Target (LOCAL)"]);assert.deepEqual(await page.locator('.modal [name="targetLocationId"] option').allTextContents(),["Bitte wählen","Source (LOCAL)","Target (LOCAL)"]);await page.locator('.modal [name="name"]').fill("Source nach Target");await page.locator('.modal [name="sourceLocationId"]').selectOption({label:"Source (LOCAL)"});await page.locator('.modal [name="targetLocationId"]').selectOption({label:"Target (LOCAL)"});await page.locator('.modal button[type="submit"]').click();await page.getByText("Source nach Target",{exact:true}).waitFor();
 assert.equal(await page.getByRole("button",{name:"Logout"}).isVisible(),true);
 await page.getByRole("button",{name:"Dashboard"}).click();await page.locator('[data-run-details="run-copy"]').click();await page.locator(".run-panel").waitFor();await page.getByText("hello.txt",{exact:true}).waitFor();await page.getByText("Kopieren",{exact:true}).waitFor();await page.getByRole("button",{name:"Schließen"}).click();
 await page.getByRole("button",{name:"Runs"}).click();await page.locator('[data-run-details="run-noop"]').click();await page.getByText("Keine Änderungen erforderlich.",{exact:true}).waitFor();await page.getByRole("button",{name:"Schließen"}).click();assert.equal(await page.getByRole("button",{name:"Logout"}).isVisible(),true);
 assert.deepEqual(responses.filter(x=>x[0]==="/api/locations"),[["/api/locations",201],["/api/locations",201]]);const locationList=await (await page.request.get(`http://127.0.0.1:${server.port}/api/locations`)).json();assert.deepEqual(locationList.data.map(x=>x.name),["Source","Target"]);assert.deepEqual(responses.filter(x=>x[0]==="/api/jobs"),[["/api/jobs",201]]);const jobList=await (await page.request.get(`http://127.0.0.1:${server.port}/api/jobs`)).json();assert.deepEqual(jobList.data.map(x=>x.name),["Source nach Target"]);assert.equal((await page.request.get(`http://127.0.0.1:${server.port}/app.js`)).headers()["cache-control"],"no-store");assert.deepEqual(pageErrors,[]);assert.deepEqual(consoleErrors,[]);
 console.log("Playwright browser smoke passed");
}finally{await browser?.close();await server.stop();await rm(root,{recursive:true,force:true})}
